### ISSUE TITLE
timeout_after value

### ISSUE THREAD

**Issue by patbegg** [michaelcarter/mixpanel-data-export-js#18]
Hi,
I've been getting an 'Expired request' error returned from Mixpanel but it appears to be fixed if i change the 'timeout_after' option to 100 instead of 10. Is this a value in seconds?

Thanks,
Pat

**Comment by benoitguigal** [comment]
+1

**Comment by michaelcarter** [comment]
Hi @patbegg, @benoitguigal. From mixpanel's API documentation: 

```
...is any UTC time in the future that represents how long you wish the request consuming data to last. For example, if you wish the request to only last 1 minute, you would calculate the UTC time as of now and then add 60 representing 1 minute ahead.
```

So to answer your question, yes, it's in seconds. I'm going to bump the default from 10 seconds to 30 in a new release, as 10 seconds seems a bit too little for some projects and I don't see too much harm in bumping it, but this option is intended to be overridden for queries that take a _long_ time.

**Comment by patbegg** [comment]
Hi,

I will be away from 15th May to 19th June. I will be collecting my email intermittently but if your request is urgent please call on +61 420 971545 and leave a message.



Thanks,

Pat
