### ISSUE TITLE
Publish v2.0.1 to npm?

### ISSUE THREAD

**Issue by JuanCaicedo** [michaelcarter/mixpanel-data-export-js#24]
If I run `npm view mixpanel-data-export-node` I see the following versions

```
[ '1.8.2', '1.8.3', '1.9.0' ]
```

Would it be possible for you to publish the new version to npm? Thanks!

**Comment by JuanCaicedo** [comment]
Never mind, I found the new version with `npm view mixpanel-data-export`. Did the module name change?

**Comment by JuanCaicedo** [comment]
Actually, I think that module is incompatible with node (I get an error when I try to require it). I gather that `mixpanel-data-export-node` is a version that is meant to work with node. Could I ask you for some clarification on that? It might be worth updating the docs to avoid confusion about which modules are still supported.

**Comment by michaelcarter** [comment]
Hi @JuanCaicedo,

`mixpanel-data-export-node` is a fork of my library by someone else. I have no control over it I'm afraid.

My library is `mixpanel-data-export`, there was a problem with `2.0.1` but I've just published `2.0.2` which should fix any node related issues. Could you give it a try and see if it works for you and let me know? I'll close this issue if so.

**Comment by JuanCaicedo** [comment]
Perfect, that makes sense, I'll know not to depend on that fork. `2.0.2` works great for me, thanks!
